### ISSUE TITLE
Include build instructions in Readme?

### ISSUE THREAD

**Issue by BenjaminMoe** [akiradeveloper/rubikmaster#37]
Can you include instructions for building the application in the Readme?

**Comment by akiradeveloper** [comment]
You can build your application using this library but what more do you what from me?

**Comment by BenjaminMoe** [comment]
https://user-images.githubusercontent.com/785824/136589675-41b90b3e-c30c-4fb3-8ab4-a0ccd89bf4fc.mov

上の動画のWASMをビルドする手順を明確に書いてくれますか？

**Comment by akiradeveloper** [comment]
OK. I wrote some note on README. You can use trunk to build the app.

**Comment by BenjaminMoe** [comment]
Great, thanks!
